# pre-commit workflow
#
# Ensures the codebase passes the pre-commit stack.

name: pre-commit

on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files --show-diff-on-failure

    - name: Check Terraform Format (AWS)
      run: |
        cd procure/aws
        terraform fmt -check

    - name: Check Terraform Format (GCP)
      run: |
        cd procure/gcp
        terraform fmt -check

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.44.1

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
